
  name: ez-lang
  version: '1.2' # just for humans, typically '1.2+git' or '1.3.2'
  summary: The new language that is EZr than Python! # 79 char long summary
  description: |
    Build entirely in C++, EZ-lang has the objective of teaching people
    just how easy programming is. We challenge people who are scared to program
    simply because it seems too hard to try our program!

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
